.TH "D:/Unity/UnityProjects/Stateless/Assets/Scripts/Player Directory Reference" 3 "Version 1.0.0" "Stateless" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/Unity/UnityProjects/Stateless/Assets/Scripts/Player Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBEvents\fP"
.br
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBGroundCharacter\&.cs\fP"
.br
.ti -1c
.RI "file \fBIPlayerMovement\&.cs\fP"
.br
.ti -1c
.RI "file \fBIPlayerMovementManager\&.cs\fP"
.br
.ti -1c
.RI "file \fBIPlayerSpawner\&.cs\fP"
.br
.ti -1c
.RI "file \fBNavMeshCharacterAnimator\&.cs\fP"
.br
.ti -1c
.RI "file \fBPlayerAnimation\&.cs\fP"
.br
.ti -1c
.RI "file \fBPlayerFire\&.cs\fP"
.br
.ti -1c
.RI "file \fBPlayerHouseController\&.cs\fP"
.br
.ti -1c
.RI "file \fBPlayerInputHandler\&.cs\fP"
.br
.ti -1c
.RI "file \fBPlayerJump\&.cs\fP"
.br
.ti -1c
.RI "file \fBPlayerMovement\&.cs\fP"
.br
.ti -1c
.RI "file \fBPlayerMovementManager\&.cs\fP"
.br
.ti -1c
.RI "file \fBPlayerNavMeshController\&.cs\fP"
.br
.ti -1c
.RI "file \fBPlayersJoining\&.cs\fP"
.br
.ti -1c
.RI "file \fBPlayerSpawner\&.cs\fP"
.br
.ti -1c
.RI "file \fBPlayersStatsManager\&.cs\fP"
.br
.ti -1c
.RI "file \fBPlayerStats\&.cs\fP"
.br
.in -1c
