.TH "GameControls.IGamePlayActions" 3 "Version 1.0.0" "Stateless" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GameControls.IGamePlayActions
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBOnMove\fP (InputAction\&.CallbackContext context)"
.br
.ti -1c
.RI "void \fBOnLook\fP (InputAction\&.CallbackContext context)"
.br
.ti -1c
.RI "void \fBOnJump\fP (InputAction\&.CallbackContext context)"
.br
.ti -1c
.RI "void \fBOnFire\fP (InputAction\&.CallbackContext context)"
.br
.ti -1c
.RI "void \fBOnJoin\fP (InputAction\&.CallbackContext context)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB419\fP of file \fBGameControls\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void GameControls\&.IGamePlayActions\&.OnFire (InputAction\&.CallbackContext context)"

.SS "void GameControls\&.IGamePlayActions\&.OnJoin (InputAction\&.CallbackContext context)"

.SS "void GameControls\&.IGamePlayActions\&.OnJump (InputAction\&.CallbackContext context)"

.SS "void GameControls\&.IGamePlayActions\&.OnLook (InputAction\&.CallbackContext context)"

.SS "void GameControls\&.IGamePlayActions\&.OnMove (InputAction\&.CallbackContext context)"


.SH "Author"
.PP 
Generated automatically by Doxygen for Stateless from the source code\&.
