.TH "D:/Unity/UnityProjects/Stateless/Assets/Scripts/Input/GameControls.cs" 3 "Version 1.0.0" "Stateless" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/Unity/UnityProjects/Stateless/Assets/Scripts/Input/GameControls.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBGameControls\fP"
.br
.ti -1c
.RI "struct \fBGameControls\&.GamePlayActions\fP"
.br
.ti -1c
.RI "interface \fBGameControls\&.IGamePlayActions\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Stateless from the source code\&.
