.TH "GameControls.GamePlayActions" 3 "Version 1.0.0" "Stateless" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GameControls.GamePlayActions
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBGamePlayActions\fP (@\fBGameControls\fP wrapper)"
.br
.ti -1c
.RI "InputActionMap \fBGet\fP ()"
.br
.ti -1c
.RI "void \fBEnable\fP ()"
.br
.ti -1c
.RI "void \fBDisable\fP ()"
.br
.ti -1c
.RI "void \fBAddCallbacks\fP (\fBIGamePlayActions\fP instance)"
.br
.ti -1c
.RI "void \fBRemoveCallbacks\fP (\fBIGamePlayActions\fP instance)"
.br
.ti -1c
.RI "void \fBSetCallbacks\fP (\fBIGamePlayActions\fP instance)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static implicit \fBoperator InputActionMap\fP (\fBGamePlayActions\fP set)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "InputAction \fBMove\fP\fC [get]\fP"
.br
.ti -1c
.RI "InputAction \fBlook\fP\fC [get]\fP"
.br
.ti -1c
.RI "InputAction \fBJump\fP\fC [get]\fP"
.br
.ti -1c
.RI "InputAction \fBFire\fP\fC [get]\fP"
.br
.ti -1c
.RI "InputAction \fBJoin\fP\fC [get]\fP"
.br
.ti -1c
.RI "bool \fBenabled\fP\fC [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB332\fP of file \fBGameControls\&.cs\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "GameControls\&.GamePlayActions\&.GamePlayActions (@\fBGameControls\fP wrapper)"

.PP
Definition at line \fB335\fP of file \fBGameControls\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void GameControls\&.GamePlayActions\&.AddCallbacks (\fBIGamePlayActions\fP instance)"

.PP
Definition at line \fB346\fP of file \fBGameControls\&.cs\fP\&.
.SS "void GameControls\&.GamePlayActions\&.Disable ()"

.PP
Definition at line \fB343\fP of file \fBGameControls\&.cs\fP\&.
.SS "void GameControls\&.GamePlayActions\&.Enable ()"

.PP
Definition at line \fB342\fP of file \fBGameControls\&.cs\fP\&.
.SS "InputActionMap GameControls\&.GamePlayActions\&.Get ()"

.PP
Definition at line \fB341\fP of file \fBGameControls\&.cs\fP\&.
.SS "static implicit GameControls\&.GamePlayActions\&.operator InputActionMap (\fBGamePlayActions\fP set)\fC [static]\fP"

.PP
Definition at line \fB345\fP of file \fBGameControls\&.cs\fP\&.
.SS "void GameControls\&.GamePlayActions\&.RemoveCallbacks (\fBIGamePlayActions\fP instance)"

.PP
Definition at line \fB386\fP of file \fBGameControls\&.cs\fP\&.
.SS "void GameControls\&.GamePlayActions\&.SetCallbacks (\fBIGamePlayActions\fP instance)"

.PP
Definition at line \fB392\fP of file \fBGameControls\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "bool GameControls\&.GamePlayActions\&.enabled\fC [get]\fP"

.PP
Definition at line \fB344\fP of file \fBGameControls\&.cs\fP\&.
.SS "InputAction GameControls\&.GamePlayActions\&.Fire\fC [get]\fP"

.PP
Definition at line \fB339\fP of file \fBGameControls\&.cs\fP\&.
.SS "InputAction GameControls\&.GamePlayActions\&.Join\fC [get]\fP"

.PP
Definition at line \fB340\fP of file \fBGameControls\&.cs\fP\&.
.SS "InputAction GameControls\&.GamePlayActions\&.Jump\fC [get]\fP"

.PP
Definition at line \fB338\fP of file \fBGameControls\&.cs\fP\&.
.SS "InputAction GameControls\&.GamePlayActions\&.look\fC [get]\fP"

.PP
Definition at line \fB337\fP of file \fBGameControls\&.cs\fP\&.
.SS "InputAction GameControls\&.GamePlayActions\&.Move\fC [get]\fP"

.PP
Definition at line \fB336\fP of file \fBGameControls\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Stateless from the source code\&.
