.TH "Stateless.Player.PlayerHouseController" 3 "Version 1.0.0" "Stateless" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Stateless.Player.PlayerHouseController
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SH "Detailed Description"
.PP 
Definition at line \fB11\fP of file \fBPlayerHouseController\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Stateless from the source code\&.
