.TH "Stateless.Player.PlayerSpawner" 3 "Version 1.0.0" "Stateless" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Stateless.Player.PlayerSpawner
.SH SYNOPSIS
.br
.PP
.PP
Inherits InjectableMonoBehaviour, and \fBStateless\&.Player\&.IPlayerSpawner\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBSpawnPlayer\fP (PlayerInput playerInput)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override void \fBAwake\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB10\fP of file \fBPlayerSpawner\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "override void Stateless\&.Player\&.PlayerSpawner\&.Awake ()\fC [protected]\fP"

.PP
Definition at line \fB16\fP of file \fBPlayerSpawner\&.cs\fP\&.
.SS "void Stateless\&.Player\&.PlayerSpawner\&.SpawnPlayer (PlayerInput playerInput)"

.PP
Implements \fBStateless\&.Player\&.IPlayerSpawner\fP\&.
.PP
Definition at line \fB23\fP of file \fBPlayerSpawner\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Stateless from the source code\&.
