.TH "Stateless.House.Events.HouseEvents" 3 "Version 1.0.0" "Stateless" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Stateless.House.Events.HouseEvents
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBStartDialogue\fP (string dialogue, CancellationToken token)"
.br
.ti -1c
.RI "void \fBEnterHouse\fP ()"
.br
.ti -1c
.RI "void \fBExitHouse\fP ()"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "static \fBHouseEvents\fP \fBInstance\fP = new()\fC [get]\fP"
.br
.in -1c
.SS "Events"

.in +1c
.ti -1c
.RI "Action< string, CancellationToken > \fBDialogueStarted\fP"
.br
.ti -1c
.RI "Action \fBHouseEntered\fP"
.br
.ti -1c
.RI "Action \fBHouseExited\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB6\fP of file \fBHouseEvents\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Stateless\&.House\&.Events\&.HouseEvents\&.EnterHouse ()"

.SS "void Stateless\&.House\&.Events\&.HouseEvents\&.ExitHouse ()"

.SS "void Stateless\&.House\&.Events\&.HouseEvents\&.StartDialogue (string dialogue, CancellationToken token)"

.SH "Property Documentation"
.PP 
.SS "\fBHouseEvents\fP Stateless\&.House\&.Events\&.HouseEvents\&.Instance = new()\fC [static]\fP, \fC [get]\fP"

.PP
Definition at line \fB8\fP of file \fBHouseEvents\&.cs\fP\&.
.SH "Event Documentation"
.PP 
.SS "Action<string, CancellationToken> Stateless\&.House\&.Events\&.HouseEvents\&.DialogueStarted"

.PP
Definition at line \fB10\fP of file \fBHouseEvents\&.cs\fP\&.
.SS "Action Stateless\&.House\&.Events\&.HouseEvents\&.HouseEntered"

.PP
Definition at line \fB11\fP of file \fBHouseEvents\&.cs\fP\&.
.SS "Action Stateless\&.House\&.Events\&.HouseEvents\&.HouseExited"

.PP
Definition at line \fB12\fP of file \fBHouseEvents\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Stateless from the source code\&.
