.TH "Stateless.Candy.Events.CandyCollected" 3 "Version 1.0.0" "Stateless" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Stateless.Candy.Events.CandyCollected
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCandyCollected\fP (Transform \fBcandyTransform\fP, int playerIndex, int candyValue)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "readonly Transform \fBcandyTransform\fP"
.br
.ti -1c
.RI "readonly int \fBPlayerIndex\fP"
.br
.ti -1c
.RI "readonly int \fBCandyValue\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB5\fP of file \fBCandyCollected\&.cs\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Stateless\&.Candy\&.Events\&.CandyCollected\&.CandyCollected (Transform candyTransform, int playerIndex, int candyValue)"

.PP
Definition at line \fB11\fP of file \fBCandyCollected\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "readonly Transform Stateless\&.Candy\&.Events\&.CandyCollected\&.candyTransform"

.PP
Definition at line \fB7\fP of file \fBCandyCollected\&.cs\fP\&.
.SS "readonly int Stateless\&.Candy\&.Events\&.CandyCollected\&.CandyValue"

.PP
Definition at line \fB9\fP of file \fBCandyCollected\&.cs\fP\&.
.SS "readonly int Stateless\&.Candy\&.Events\&.CandyCollected\&.PlayerIndex"

.PP
Definition at line \fB8\fP of file \fBCandyCollected\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Stateless from the source code\&.
