.TH "Stateless.Player.Events.PlayerSpawned" 3 "Version 1.0.0" "Stateless" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Stateless.Player.Events.PlayerSpawned
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPlayerSpawned\fP (\fBPlayerStats\fP playerStats)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "readonly \fBPlayerStats\fP \fBPlayerStats\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB3\fP of file \fBPlayerSpawned\&.cs\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Stateless\&.Player\&.Events\&.PlayerSpawned\&.PlayerSpawned (\fBPlayerStats\fP playerStats)"

.PP
Definition at line \fB7\fP of file \fBPlayerSpawned\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "readonly \fBPlayerStats\fP Stateless\&.Player\&.Events\&.PlayerSpawned\&.PlayerStats"

.PP
Definition at line \fB5\fP of file \fBPlayerSpawned\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Stateless from the source code\&.
