.TH "Stateless.Candy" 3 "Version 1.0.0" "Stateless" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Stateless.Candy
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBEvents\fP"
.br
.in -1c
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCandyManager\fP"
.br
.ti -1c
.RI "class \fBUICandyToStats\fP"
.br
.ti -1c
.RI "class \fBWorldCandy\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Stateless from the source code\&.
