.TH "Stateless.Zombies.ZombieDamage" 3 "Version 1.0.0" "Stateless" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Stateless.Zombies.ZombieDamage
.SH SYNOPSIS
.br
.PP
.PP
Inherits InjectableMonoBehaviour, and \fBStateless\&.Zombies\&.IDamageable\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBTakeDamage\fP (int damageAmount)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override void \fBAwake\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB6\fP of file \fBZombieDamage\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "override void Stateless\&.Zombies\&.ZombieDamage\&.Awake ()\fC [protected]\fP"

.PP
Definition at line \fB9\fP of file \fBZombieDamage\&.cs\fP\&.
.SS "void Stateless\&.Zombies\&.ZombieDamage\&.TakeDamage (int damageAmount)"

.PP
Implements \fBStateless\&.Zombies\&.IDamageable\fP\&.
.PP
Definition at line \fB15\fP of file \fBZombieDamage\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Stateless from the source code\&.
