.TH "Stateless.WayPointSystem.WaypointSystem" 3 "Version 1.0.0" "Stateless" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Stateless.WayPointSystem.WaypointSystem
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "Transform \fBGetWaypoint\fP (int index)"
.br
.ti -1c
.RI "int \fBGetWaypointsCount\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB6\fP of file \fBWaypointSystem\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "Transform Stateless\&.WayPointSystem\&.WaypointSystem\&.GetWaypoint (int index)"

.SS "int Stateless\&.WayPointSystem\&.WaypointSystem\&.GetWaypointsCount ()"


.SH "Author"
.PP 
Generated automatically by Doxygen for Stateless from the source code\&.
