.TH "Stateless.House.HouseStep" 3 "Version 1.0.0" "Stateless" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Stateless.House.HouseStep
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "AudioClip \fBVoiceOver\fP"
.br
.ti -1c
.RI "List< GameObject > \fBGameObjectsToActivate\fP"
.br
.ti -1c
.RI "Color \fBTintColor\fP = Color\&.white"
.br
.ti -1c
.RI "string \fBDialogText\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB8\fP of file \fBHouseStep\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "string Stateless\&.House\&.HouseStep\&.DialogText"

.PP
Definition at line \fB13\fP of file \fBHouseStep\&.cs\fP\&.
.SS "List<GameObject> Stateless\&.House\&.HouseStep\&.GameObjectsToActivate"

.PP
Definition at line \fB11\fP of file \fBHouseStep\&.cs\fP\&.
.SS "Color Stateless\&.House\&.HouseStep\&.TintColor = Color\&.white"

.PP
Definition at line \fB12\fP of file \fBHouseStep\&.cs\fP\&.
.SS "AudioClip Stateless\&.House\&.HouseStep\&.VoiceOver"

.PP
Definition at line \fB10\fP of file \fBHouseStep\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Stateless from the source code\&.
