.TH "Stateless.Player.PlayerStats" 3 "Version 1.0.0" "Stateless" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Stateless.Player.PlayerStats
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPlayerStats\fP (GameObject playerInstance, int playerIndex, float initialHealth, int initialCandies)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "int \fBPlayerIndex\fP\fC [get]\fP"
.br
.ti -1c
.RI "GameObject \fBPlayerInstance\fP\fC [get]\fP"
.br
.ti -1c
.RI "float \fBHealth\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "int \fBCandies\fP\fC [get, set]\fP"
.br
.in -1c
.SS "Events"

.in +1c
.ti -1c
.RI "Action< float, int > \fBHealthChanged\fP"
.br
.ti -1c
.RI "Action< int, int > \fBCandyCountChanged\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB6\fP of file \fBPlayerStats\&.cs\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Stateless\&.Player\&.PlayerStats\&.PlayerStats (GameObject playerInstance, int playerIndex, float initialHealth, int initialCandies)"

.PP
Definition at line \fB36\fP of file \fBPlayerStats\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "int Stateless\&.Player\&.PlayerStats\&.Candies\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line \fB23\fP of file \fBPlayerStats\&.cs\fP\&.
.SS "float Stateless\&.Player\&.PlayerStats\&.Health\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line \fB12\fP of file \fBPlayerStats\&.cs\fP\&.
.SS "int Stateless\&.Player\&.PlayerStats\&.PlayerIndex\fC [get]\fP"

.PP
Definition at line \fB8\fP of file \fBPlayerStats\&.cs\fP\&.
.SS "GameObject Stateless\&.Player\&.PlayerStats\&.PlayerInstance\fC [get]\fP"

.PP
Definition at line \fB9\fP of file \fBPlayerStats\&.cs\fP\&.
.SH "Event Documentation"
.PP 
.SS "Action<int, int> Stateless\&.Player\&.PlayerStats\&.CandyCountChanged"

.PP
Definition at line \fB34\fP of file \fBPlayerStats\&.cs\fP\&.
.SS "Action<float, int> Stateless\&.Player\&.PlayerStats\&.HealthChanged"

.PP
Definition at line \fB33\fP of file \fBPlayerStats\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Stateless from the source code\&.
