.TH "Stateless.Zombies.Zombie" 3 "Version 1.0.0" "Stateless" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Stateless.Zombies.Zombie
.SH SYNOPSIS
.br
.PP
.PP
Inherits InjectableMonoBehaviour\&.
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "bool \fBIsDying\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB13\fP of file \fBZombie\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "bool Stateless\&.Zombies\&.Zombie\&.IsDying"

.PP
Definition at line \fB36\fP of file \fBZombie\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Stateless from the source code\&.
