.TH "Stateless.Player.IPlayerMovementManager" 3 "Version 1.0.0" "Stateless" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Stateless.Player.IPlayerMovementManager
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBStateless\&.Player\&.PlayerMovementManager\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBRegisterPlayer\fP (\fBIPlayerMovement\fP player)"
.br
.ti -1c
.RI "void \fBRemovePlayer\fP (\fBIPlayerMovement\fP player)"
.br
.ti -1c
.RI "void \fBSetInput\fP (int index, Vector2 input)"
.br
.ti -1c
.RI "void \fBJump\fP (int playerIndex)"
.br
.ti -1c
.RI "void \fBFire\fP (int playerIndex)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB6\fP of file \fBIPlayerMovementManager\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Stateless\&.Player\&.IPlayerMovementManager\&.Fire (int playerIndex)"

.PP
Implemented in \fBStateless\&.Player\&.PlayerMovementManager\fP\&.
.SS "void Stateless\&.Player\&.IPlayerMovementManager\&.Jump (int playerIndex)"

.PP
Implemented in \fBStateless\&.Player\&.PlayerMovementManager\fP\&.
.SS "void Stateless\&.Player\&.IPlayerMovementManager\&.RegisterPlayer (\fBIPlayerMovement\fP player)"

.PP
Implemented in \fBStateless\&.Player\&.PlayerMovementManager\fP\&.
.SS "void Stateless\&.Player\&.IPlayerMovementManager\&.RemovePlayer (\fBIPlayerMovement\fP player)"

.PP
Implemented in \fBStateless\&.Player\&.PlayerMovementManager\fP\&.
.SS "void Stateless\&.Player\&.IPlayerMovementManager\&.SetInput (int index, Vector2 input)"

.PP
Implemented in \fBStateless\&.Player\&.PlayerMovementManager\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Stateless from the source code\&.
