.TH "Stateless.Fire.GameObjectPool" 3 "Version 1.0.0" "Stateless" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Stateless.Fire.GameObjectPool
.SH SYNOPSIS
.br
.PP
.PP
Inherits ScriptableObject\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBPrewarm\fP (string prentTransformName=null)"
.br
.RI "Prewarms the pool with the specified prewarm Count on the GameObjectPool Scriptable Object\&. "
.ti -1c
.RI "GameObject \fBGet\fP ()"
.br
.RI "Fetches the next GameObject from the pool\&. "
.ti -1c
.RI "async void \fBReturnToPool\fP (GameObject objectToReturn, float delay=0)"
.br
.RI "Returns a GameObject to the pool to be recycled\&. "
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB9\fP of file \fBGameObjectPool\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "GameObject Stateless\&.Fire\&.GameObjectPool\&.Get ()"

.PP
Fetches the next GameObject from the pool\&. 
.PP
\fBReturns\fP
.RS 4
An instance of the pooled GameObject
.RE
.PP

.PP
Definition at line \fB44\fP of file \fBGameObjectPool\&.cs\fP\&.
.SS "void Stateless\&.Fire\&.GameObjectPool\&.Prewarm (string prentTransformName = \fCnull\fP)"

.PP
Prewarms the pool with the specified prewarm Count on the GameObjectPool Scriptable Object\&. 
.PP
\fBParameters\fP
.RS 4
\fIprentTransformName\fP [Optional] If ignored, all pool objects will be grouped into one parent transform
.RE
.PP

.PP
Definition at line \fB20\fP of file \fBGameObjectPool\&.cs\fP\&.
.SS "async void Stateless\&.Fire\&.GameObjectPool\&.ReturnToPool (GameObject objectToReturn, float delay = \fC0\fP)"

.PP
Returns a GameObject to the pool to be recycled\&. 
.PP
\fBParameters\fP
.RS 4
\fIobjectToReturn\fP An instance of the pooled gameObject implementing IGameObjectPooled
.br
\fIdelay\fP An optional delay of n milli seconds in which all all renders are disabled for any jobs to be handled asynchrounsly 
.RE
.PP

.PP
Definition at line \fB73\fP of file \fBGameObjectPool\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Stateless from the source code\&.
