.TH "Stateless.Zombies.IDamageable" 3 "Version 1.0.0" "Stateless" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Stateless.Zombies.IDamageable
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBStateless\&.Zombies\&.ZombieDamage\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBTakeDamage\fP (int damageAmount)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB3\fP of file \fBIDamageable\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Stateless\&.Zombies\&.IDamageable\&.TakeDamage (int damageAmount)"

.PP
Implemented in \fBStateless\&.Zombies\&.ZombieDamage\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Stateless from the source code\&.
