.TH "Stateless.House.GreenHouse" 3 "Version 1.0.0" "Stateless" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Stateless.House.GreenHouse
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBStateless\&.House\&.BaseHouse\fP\&.
.SS "Additional Inherited Members"


Public Member Functions inherited from \fBStateless\&.House\&.BaseHouse\fP
.in +1c
.ti -1c
.RI "virtual async UniTask \fBEnterHouseAsync\fP (CancellationToken token, int playerIndex)"
.br
.ti -1c
.RI "virtual async UniTask \fBUpdateHouseAsync\fP (CancellationToken token)"
.br
.ti -1c
.RI "void \fBProceedToNextStep\fP ()"
.br
.ti -1c
.RI "virtual async UniTask \fBExitHouseAsync\fP (CancellationToken token)"
.br
.in -1c

Protected Attributes inherited from \fBStateless\&.House\&.BaseHouse\fP
.in +1c
.ti -1c
.RI "string \fBhouseName\fP"
.br
.ti -1c
.RI "int \fBinitialCandyInventory\fP"
.br
.ti -1c
.RI "int \fBcandyCountPerCollection\fP"
.br
.ti -1c
.RI "List< \fBHouseStep\fP > \fBSteps\fP"
.br
.in -1c

Properties inherited from \fBStateless\&.House\&.BaseHouse\fP
.in +1c
.ti -1c
.RI "string \fBHouseName\fP\fC [get]\fP"
.br
.in -1c

Properties inherited from \fBStateless\&.House\&.IHouse\fP

Events inherited from \fBStateless\&.House\&.BaseHouse\fP
.in +1c
.ti -1c
.RI "Action< int, int > \fBCandyCollected\fP"
.br
.ti -1c
.RI "Action< \fBIHouse\fP > \fBHouseEntered\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB5\fP of file \fBGreenHouse\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Stateless from the source code\&.
