.TH "Stateless.Candy.Events" 3 "Version 1.0.0" "Stateless" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Stateless.Candy.Events
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCandyCollected\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Stateless from the source code\&.
