.TH "Stateless.Candy.UICandyToStats" 3 "Version 1.0.0" "Stateless" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Stateless.Candy.UICandyToStats
.SH SYNOPSIS
.br
.PP
.PP
Inherits InjectableMonoBehaviour\&.
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override void \fBAwake\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB9\fP of file \fBUICandyToStats\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "override void Stateless\&.Candy\&.UICandyToStats\&.Awake ()\fC [protected]\fP"

.PP
Definition at line \fB16\fP of file \fBUICandyToStats\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Stateless from the source code\&.
