.TH "Stateless.Player.IPlayerMovement" 3 "Version 1.0.0" "Stateless" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Stateless.Player.IPlayerMovement
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBStateless\&.Player\&.PlayerMovement\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBSetInput\fP (Vector2 input)"
.br
.ti -1c
.RI "void \fBJump\fP ()"
.br
.ti -1c
.RI "void \fBFire\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB5\fP of file \fBIPlayerMovement\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Stateless\&.Player\&.IPlayerMovement\&.Fire ()"

.PP
Implemented in \fBStateless\&.Player\&.PlayerMovement\fP\&.
.SS "void Stateless\&.Player\&.IPlayerMovement\&.Jump ()"

.PP
Implemented in \fBStateless\&.Player\&.PlayerMovement\fP\&.
.SS "void Stateless\&.Player\&.IPlayerMovement\&.SetInput (Vector2 input)"

.PP
Implemented in \fBStateless\&.Player\&.PlayerMovement\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Stateless from the source code\&.
