.TH "Stateless.Player.PlayerFire" 3 "Version 1.0.0" "Stateless" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Stateless.Player.PlayerFire
.SH SYNOPSIS
.br
.PP
.PP
Inherits InjectableMonoBehaviour\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBFire\fP ()"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override void \fBAwake\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB7\fP of file \fBPlayerFire\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "override void Stateless\&.Player\&.PlayerFire\&.Awake ()\fC [protected]\fP"

.PP
Definition at line \fB12\fP of file \fBPlayerFire\&.cs\fP\&.
.SS "void Stateless\&.Player\&.PlayerFire\&.Fire ()"

.PP
Definition at line \fB17\fP of file \fBPlayerFire\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Stateless from the source code\&.
