.TH "Stateless.Zombies.Events.ZombieSpawned" 3 "Version 1.0.0" "Stateless" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Stateless.Zombies.Events.ZombieSpawned
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBZombieSpawned\fP (\fBZombie\fP zombieInstance)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "readonly \fBZombie\fP \fBZombieInstance\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB5\fP of file \fBZombieSpawned\&.cs\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Stateless\&.Zombies\&.Events\&.ZombieSpawned\&.ZombieSpawned (\fBZombie\fP zombieInstance)"

.PP
Definition at line \fB9\fP of file \fBZombieSpawned\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "readonly \fBZombie\fP Stateless\&.Zombies\&.Events\&.ZombieSpawned\&.ZombieInstance"

.PP
Definition at line \fB7\fP of file \fBZombieSpawned\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Stateless from the source code\&.
