.TH "Stateless.Zombies.Events.PlayerDamaged" 3 "Version 1.0.0" "Stateless" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Stateless.Zombies.Events.PlayerDamaged
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPlayerDamaged\fP (float damage, int playerIndex)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "readonly float \fBDamage\fP"
.br
.ti -1c
.RI "readonly int \fBPlayerIndex\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB3\fP of file \fBPlayerDamaged\&.cs\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Stateless\&.Zombies\&.Events\&.PlayerDamaged\&.PlayerDamaged (float damage, int playerIndex)"

.PP
Definition at line \fB8\fP of file \fBPlayerDamaged\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "readonly float Stateless\&.Zombies\&.Events\&.PlayerDamaged\&.Damage"

.PP
Definition at line \fB5\fP of file \fBPlayerDamaged\&.cs\fP\&.
.SS "readonly int Stateless\&.Zombies\&.Events\&.PlayerDamaged\&.PlayerIndex"

.PP
Definition at line \fB6\fP of file \fBPlayerDamaged\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Stateless from the source code\&.
