.TH "Stateless.Player.PlayersJoining" 3 "Version 1.0.0" "Stateless" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Stateless.Player.PlayersJoining
.SH SYNOPSIS
.br
.PP
.PP
Inherits InjectableMonoBehaviour\&.
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override void \fBAwake\fP ()"
.br
.in -1c
.SS "Events"

.in +1c
.ti -1c
.RI "static Action< int > \fBOnPlayerJoined\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB8\fP of file \fBPlayersJoining\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "override void Stateless\&.Player\&.PlayersJoining\&.Awake ()\fC [protected]\fP"

.PP
Definition at line \fB16\fP of file \fBPlayersJoining\&.cs\fP\&.
.SH "Event Documentation"
.PP 
.SS "Action<int> Stateless\&.Player\&.PlayersJoining\&.OnPlayerJoined\fC [static]\fP"

.PP
Definition at line \fB12\fP of file \fBPlayersJoining\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Stateless from the source code\&.
