.TH "Stateless.Player.PlayerInputHandler" 3 "Version 1.0.0" "Stateless" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Stateless.Player.PlayerInputHandler
.SH SYNOPSIS
.br
.PP
.PP
Inherits InjectableMonoBehaviour\&.
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override void \fBAwake\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB8\fP of file \fBPlayerInputHandler\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "override void Stateless\&.Player\&.PlayerInputHandler\&.Awake ()\fC [protected]\fP"

.PP
Definition at line \fB18\fP of file \fBPlayerInputHandler\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Stateless from the source code\&.
