.TH "Stateless.Fire.IGameObjectPooled" 3 "Version 1.0.0" "Stateless" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Stateless.Fire.IGameObjectPooled \- Provides access to the Pool\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBStateless\&.Fire\&.Bullet_3D\fP\&.
.SS "Properties"

.in +1c
.ti -1c
.RI "\fBGameObjectPool\fP \fBPool\fP\fC [get, set]\fP"
.br
.RI "This is your reference to the pool which you will use to return gameObjects no longer needed\&. "
.in -1c
.SH "Detailed Description"
.PP 
Provides access to the Pool\&. 
.PP
Definition at line \fB98\fP of file \fBGameObjectPool\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "\fBGameObjectPool\fP Stateless\&.Fire\&.IGameObjectPooled\&.Pool\fC [get]\fP, \fC [set]\fP"

.PP
This is your reference to the pool which you will use to return gameObjects no longer needed\&. 
.PP
Implemented in \fBStateless\&.Fire\&.Bullet_3D\fP\&.
.PP
Definition at line \fB103\fP of file \fBGameObjectPool\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Stateless from the source code\&.
