.TH "Stateless.Player.PlayerMovementManager" 3 "Version 1.0.0" "Stateless" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Stateless.Player.PlayerMovementManager
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBStateless\&.Player\&.IPlayerMovementManager\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBRegisterPlayer\fP (\fBIPlayerMovement\fP player)"
.br
.ti -1c
.RI "void \fBRemovePlayer\fP (\fBIPlayerMovement\fP player)"
.br
.ti -1c
.RI "void \fBSetInput\fP (int index, Vector2 input)"
.br
.ti -1c
.RI "void \fBJump\fP (int playerIndex)"
.br
.ti -1c
.RI "void \fBFire\fP (int playerIndex)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "Dictionary< int, \fBIPlayerMovement\fP > \fBPlayerMovements\fP\fC [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB8\fP of file \fBPlayerMovementManager\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Stateless\&.Player\&.PlayerMovementManager\&.Fire (int playerIndex)"

.PP
Implements \fBStateless\&.Player\&.IPlayerMovementManager\fP\&.
.PP
Definition at line \fB45\fP of file \fBPlayerMovementManager\&.cs\fP\&.
.SS "void Stateless\&.Player\&.PlayerMovementManager\&.Jump (int playerIndex)"

.PP
Implements \fBStateless\&.Player\&.IPlayerMovementManager\fP\&.
.PP
Definition at line \fB37\fP of file \fBPlayerMovementManager\&.cs\fP\&.
.SS "void Stateless\&.Player\&.PlayerMovementManager\&.RegisterPlayer (\fBIPlayerMovement\fP player)"

.PP
Implements \fBStateless\&.Player\&.IPlayerMovementManager\fP\&.
.PP
Definition at line \fB14\fP of file \fBPlayerMovementManager\&.cs\fP\&.
.SS "void Stateless\&.Player\&.PlayerMovementManager\&.RemovePlayer (\fBIPlayerMovement\fP player)"

.PP
Implements \fBStateless\&.Player\&.IPlayerMovementManager\fP\&.
.PP
Definition at line \fB24\fP of file \fBPlayerMovementManager\&.cs\fP\&.
.SS "void Stateless\&.Player\&.PlayerMovementManager\&.SetInput (int index, Vector2 input)"

.PP
Implements \fBStateless\&.Player\&.IPlayerMovementManager\fP\&.
.PP
Definition at line \fB29\fP of file \fBPlayerMovementManager\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "Dictionary<int, \fBIPlayerMovement\fP> Stateless\&.Player\&.PlayerMovementManager\&.PlayerMovements\fC [get]\fP"

.PP
Definition at line \fB12\fP of file \fBPlayerMovementManager\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Stateless from the source code\&.
