.TH "Stateless.Fire.Bullet_3D" 3 "Version 1.0.0" "Stateless" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Stateless.Fire.Bullet_3D
.SH SYNOPSIS
.br
.PP
.PP
Inherits InjectableMonoBehaviour, and \fBStateless\&.Fire\&.IGameObjectPooled\fP\&.
.SS "Properties"

.in +1c
.ti -1c
.RI "\fBGameObjectPool\fP \fBPool\fP\fC [get, set]\fP"
.br
.RI "This is your reference to the pool which you will use to return gameObjects no longer needed\&. "
.in -1c

Properties inherited from \fBStateless\&.Fire\&.IGameObjectPooled\fP
.SH "Detailed Description"
.PP 
Definition at line \fB9\fP of file \fBBullet_3D\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "\fBGameObjectPool\fP Stateless\&.Fire\&.Bullet_3D\&.Pool\fC [get]\fP, \fC [set]\fP"

.PP
This is your reference to the pool which you will use to return gameObjects no longer needed\&. 
.PP
Implements \fBStateless\&.Fire\&.IGameObjectPooled\fP\&.
.PP
Definition at line \fB20\fP of file \fBBullet_3D\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Stateless from the source code\&.
