.TH "Stateless.Player.PlayerMovement" 3 "Version 1.0.0" "Stateless" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Stateless.Player.PlayerMovement
.SH SYNOPSIS
.br
.PP
.PP
Inherits InjectableMonoBehaviour, and \fBStateless\&.Player\&.IPlayerMovement\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBDestroyPlayer\fP ()"
.br
.ti -1c
.RI "void \fBSetInput\fP (Vector2 input)"
.br
.ti -1c
.RI "void \fBJump\fP ()"
.br
.ti -1c
.RI "void \fBFire\fP ()"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override void \fBAwake\fP ()"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "int \fBPlayerIndex\fP\fC [get]\fP"
.br
.ti -1c
.RI "float \fBSpeed\fP\fC [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB9\fP of file \fBPlayerMovement\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "override void Stateless\&.Player\&.PlayerMovement\&.Awake ()\fC [protected]\fP"

.PP
Definition at line \fB26\fP of file \fBPlayerMovement\&.cs\fP\&.
.SS "void Stateless\&.Player\&.PlayerMovement\&.DestroyPlayer ()"

.PP
Definition at line \fB42\fP of file \fBPlayerMovement\&.cs\fP\&.
.SS "void Stateless\&.Player\&.PlayerMovement\&.Fire ()"

.PP
Implements \fBStateless\&.Player\&.IPlayerMovement\fP\&.
.SS "void Stateless\&.Player\&.PlayerMovement\&.Jump ()"

.PP
Implements \fBStateless\&.Player\&.IPlayerMovement\fP\&.
.SS "void Stateless\&.Player\&.PlayerMovement\&.SetInput (Vector2 input)"

.PP
Implements \fBStateless\&.Player\&.IPlayerMovement\fP\&.
.PP
Definition at line \fB48\fP of file \fBPlayerMovement\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "int Stateless\&.Player\&.PlayerMovement\&.PlayerIndex\fC [get]\fP"

.PP
Definition at line \fB15\fP of file \fBPlayerMovement\&.cs\fP\&.
.SS "float Stateless\&.Player\&.PlayerMovement\&.Speed\fC [get]\fP"

.PP
Definition at line \fB17\fP of file \fBPlayerMovement\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Stateless from the source code\&.
