.TH "Stateless.WayPointSystem.WaypointFollower" 3 "Version 1.0.0" "Stateless" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Stateless.WayPointSystem.WaypointFollower
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBGoTo\fP (int targetIndex)"
.br
.ti -1c
.RI "void \fBGoToNext\fP ()"
.br
.ti -1c
.RI "void \fBGoToPrevious\fP ()"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "float \fBMoveSpeed\fP\fC [get]\fP"
.br
.ti -1c
.RI "float \fBCurrentSmoothSpeed\fP\fC [get]\fP"
.br
.in -1c
.SS "Events"

.in +1c
.ti -1c
.RI "Action< Transform > \fBOnTargetReached\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB10\fP of file \fBWaypointFollower\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Stateless\&.WayPointSystem\&.WaypointFollower\&.GoTo (int targetIndex)"

.PP
Definition at line \fB34\fP of file \fBWaypointFollower\&.cs\fP\&.
.SS "void Stateless\&.WayPointSystem\&.WaypointFollower\&.GoToNext ()"

.SS "void Stateless\&.WayPointSystem\&.WaypointFollower\&.GoToPrevious ()"

.SH "Property Documentation"
.PP 
.SS "float Stateless\&.WayPointSystem\&.WaypointFollower\&.CurrentSmoothSpeed\fC [get]\fP"

.PP
Definition at line \fB17\fP of file \fBWaypointFollower\&.cs\fP\&.
.SS "float Stateless\&.WayPointSystem\&.WaypointFollower\&.MoveSpeed\fC [get]\fP"

.PP
Definition at line \fB16\fP of file \fBWaypointFollower\&.cs\fP\&.
.SH "Event Documentation"
.PP 
.SS "Action<Transform> Stateless\&.WayPointSystem\&.WaypointFollower\&.OnTargetReached"

.PP
Definition at line \fB22\fP of file \fBWaypointFollower\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Stateless from the source code\&.
