.TH "Stateless.Zombies" 3 "Version 1.0.0" "Stateless" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Stateless.Zombies
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBEvents\fP"
.br
.in -1c
.SS "Classes"

.in +1c
.ti -1c
.RI "interface \fBIDamageable\fP"
.br
.ti -1c
.RI "class \fBZombie\fP"
.br
.ti -1c
.RI "class \fBZombieDamage\fP"
.br
.ti -1c
.RI "class \fBZombieSpawner\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Stateless from the source code\&.
