.TH "Stateless.Candy.CandyManager" 3 "Version 1.0.0" "Stateless" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Stateless.Candy.CandyManager
.SH SYNOPSIS
.br
.PP
.PP
Inherits PersistentSingleton< CandyManager >\&.
.SS "Events"

.in +1c
.ti -1c
.RI "Action \fBOnGameOver\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB11\fP of file \fBCandyManager\&.cs\fP\&.
.SH "Event Documentation"
.PP 
.SS "Action Stateless\&.Candy\&.CandyManager\&.OnGameOver"

.PP
Definition at line \fB15\fP of file \fBCandyManager\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Stateless from the source code\&.
