.TH "Stateless.Player.Events.BulletFired" 3 "Version 1.0.0" "Stateless" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Stateless.Player.Events.BulletFired
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBBulletFired\fP (AudioClip sfx, Vector3 transformPosition)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "readonly AudioClip \fBSfx\fP"
.br
.ti -1c
.RI "readonly Vector3 \fBTransformPosition\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB5\fP of file \fBBulletFired\&.cs\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Stateless\&.Player\&.Events\&.BulletFired\&.BulletFired (AudioClip sfx, Vector3 transformPosition)"

.PP
Definition at line \fB9\fP of file \fBBulletFired\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "readonly AudioClip Stateless\&.Player\&.Events\&.BulletFired\&.Sfx"

.PP
Definition at line \fB7\fP of file \fBBulletFired\&.cs\fP\&.
.SS "readonly Vector3 Stateless\&.Player\&.Events\&.BulletFired\&.TransformPosition"

.PP
Definition at line \fB8\fP of file \fBBulletFired\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Stateless from the source code\&.
