.TH "Stateless.Player.PlayersStatsManager" 3 "Version 1.0.0" "Stateless" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Stateless.Player.PlayersStatsManager
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBAddPlayer\fP (\fBPlayerStats\fP playerStat)"
.br
.ti -1c
.RI "void \fBRemovePlayer\fP (\fBPlayerStats\fP playerStat)"
.br
.ti -1c
.RI "List< \fBPlayerStats\fP > \fBGetPlayers\fP ()"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "static \fBPlayersStatsManager\fP \fBInstance\fP\fC [get]\fP"
.br
.ti -1c
.RI "IReadOnlyList< \fBPlayerStats\fP > \fBPlayerStats\fP\fC [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB6\fP of file \fBPlayersStatsManager\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Stateless\&.Player\&.PlayersStatsManager\&.AddPlayer (\fBPlayerStats\fP playerStat)"

.SS "List< \fBPlayerStats\fP > Stateless\&.Player\&.PlayersStatsManager\&.GetPlayers ()"

.SS "void Stateless\&.Player\&.PlayersStatsManager\&.RemovePlayer (\fBPlayerStats\fP playerStat)"

.SH "Property Documentation"
.PP 
.SS "\fBPlayersStatsManager\fP Stateless\&.Player\&.PlayersStatsManager\&.Instance\fC [static]\fP, \fC [get]\fP"

.PP
Definition at line \fB10\fP of file \fBPlayersStatsManager\&.cs\fP\&.
.SS "IReadOnlyList<\fBPlayerStats\fP> Stateless\&.Player\&.PlayersStatsManager\&.PlayerStats\fC [get]\fP"

.PP
Definition at line \fB14\fP of file \fBPlayersStatsManager\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Stateless from the source code\&.
