.TH "Stateless.WayPointSystem" 3 "Version 1.0.0" "Stateless" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Stateless.WayPointSystem
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBWaypointFollower\fP"
.br
.ti -1c
.RI "class \fBWaypointSystem\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Stateless from the source code\&.
