name: Generate Class Diagrams

on:
  push:
    branches:
      - main

jobs:
  generate-class-diagrams:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Doxygen and Graphviz
        run: sudo apt-get install -y doxygen graphviz

      - name: Prepare Directories
        run: |
          mkdir -p ./docs
          mkdir -p ./mermaid-diagrams

      - name: Generate Documentation
        run: |
          # Create a Doxygen configuration file
          echo "PROJECT_NAME = My Class Diagrams" > Doxyfile
          echo "OUTPUT_DIRECTORY = ./docs" >> Doxyfile
          echo "INPUT = ./Assets/Scripts" >> Doxyfile  # Adjust the input path
          echo "GENERATE_HTML = NO" >> Doxyfile
          echo "GENERATE_LATEX = NO" >> Doxyfile
          echo "CLASS_DIAGRAMS = YES" >> Doxyfile

          # Generate documentation with class diagrams
          doxygen Doxyfile

      - name: Convert to Mermaid
        run: |
          # Convert Graphviz diagrams to Mermaid format
          find ./docs -name '*.dot' -exec dot -Tmermaid -o ./mermaid-diagrams/{}-converted.mmd {} \;

      - name: Save Mermaid Diagrams
        run: |
          # Move Mermaid diagrams to a desired location
          mv ./mermaid-diagrams/*.mmd ./

      - name: Clean Up
        run: |
          # Clean up intermediate files
          rm -r ./docs
          rm -r ./mermaid-diagrams