name: Generate Class Diagrams

on:
  push:
    branches:
      - main

jobs:
  generate-class-diagrams:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Doxygen and Graphviz
        run: sudo apt-get install -y doxygen graphviz

      - name: Prepare Directories
        run: |
          mkdir -p ./docs
          mkdir -p ./mermaid-diagrams

      - name: Create Doxyfile
        run: |
          PROJECT_NAME           = 'My Class Diagrams'
          OUTPUT_DIRECTORY       = docs
          INPUT                  = ./Assets/Scripts
          RECURSIVE              = YES  # Recursively include subdirectories
          GENERATE_HTML          = NO
          GENERATE_LATEX         = NO
          CLASS_DIAGRAMS         = YES




          # Generate documentation with class diagrams
          doxygen Doxyfile

      - name: Convert to Mermaid
        run: |
          # Convert Graphviz diagrams to Mermaid format
          find ./docs -name '*.dot' -exec dot -Tmermaid -o ./mermaid-diagrams/{}-converted.mmd {} \;

      - name: Debug Files in mermaid-diagrams
        run: ls -R $GITHUB_WORKSPACE/mermaid-diagrams


      - name: Move Mermaid diagrams to a desired location
        run: |
          mkdir -p ./diagrams
          mv $GITHUB_WORKSPACE/mermaid-diagrams/*.mmd ./diagrams/



      # - name: Clean Up
      #   run: |
      #     # Clean up intermediate files
      #     rm -r ./docs
      #     rm -r ./mermaid-diagrams

      - name: Commit and Push Changes
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git add ./diagrams/*.mmd
          git commit -m "Update class diagrams in Mermaid format"
          git push origin main  # Adjust to your branch name if needed

      